<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class BaseModel extends Model
{
    public $incrementing = false;

    protected static function boot()
    {
	    parent::boot(); // TODO: Change the autogenerated stub
	    static::creating(function ($model) {
	    	$model->id = Str::uuid();
	    });
    }
}