<?php

namespace App\Models;

use Illuminate\Http\Request;
use Carbon\Carbon;

class Classes extends BaseModel
{
    protected $table = 'class';
    protected $appends = ['status'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
	    static::creating(function ($model) {
	    	$model->slug = str_slug($model->class_name);
	    });
    }

    protected function findBySlug($slug)
    {
        return $this->where('slug', $slug)->first();
    }

    public function getStatusAttribute()
    {
        return $this->class_status ? "<i class='fas fa-check text-success'></i> Aktif" : "<i class='fas fa-times text-danger'></i> Tidak Aktif";
    }

    public function scopeFilter($query, Request $request)
    {
        if ($request->has('class_name') && !empty($request->get('class_name'))) {
            $search = strtolower($request->get('class_name'));
            $query->whereRaw('lower(class_name) like ?', '%'. $search .'%');
        }
        return $query;
    }

    public function site()
    {
        return $this->belongsTo('App\Models\Site', 'site_id', 'id');
    }

    public function trainings()
    {
        return $this->hasMany('App\Models\Training', 'class_id');
    }

    public function reservations()
    {
        return $this->hasManyThrough('App\Models\Reservation', 'App\Models\Training', 'class_id', 'training_id');
    }
}
