<?php

namespace App\Models;

use Illuminate\Http\Request;

class Identity extends BaseModel
{
    protected $table = 'identity';
    protected $appends = ['status'];

    protected $fillable = ['user_id', 'full_name', 'email', 'site_id', 'department_id', 'organization_id'];

    // protected static function boot()
    // {
    //     parent::boot(); // TODO: Change the autogenerated stub
	//     static::creating(function ($model) {
	//     	$model->slug = str_slug($model->site_name);
	//     });
    // }

    public function getStatusAttribute()
    {
        return $this->identity_status ? "<i class='fas fa-check text-success'></i> Aktif" : "<i class='fas fa-times text-danger'></i> Tidak Aktif";
    }

    public function scopeFilter($query, Request $request)
    {
        if ($request->has('full_name') && !empty($request->get('full_name'))) {
            $search = strtolower($request->get('full_name'));
            $query->whereRaw('lower(full_name) like ?', '%'. $search .'%');
        }
        
        if ($request->has('email') && !empty($request->get('email'))) {
            $query->where('email', $email);
        }

        return $query;
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function department()
    {
        return $this->belongsTo('App\Models\Department');
    }

    public function directorate()
    {
        return $this->belongsTo('App\Models\Directorate');
    }

    public function organization()
    {
        return $this->belongsTo('App\Models\Organization');
    }

    public function site()
    {
        return $this->belongsTo('App\Models\Site');
    }

    public function unit()
    {
        return $this->belongsTo('App\Models\Unit');
    }

}
