<?php

namespace App\Models;

use Illuminate\Http\Request;

class Site extends BaseModel
{
    protected $table = 'site';
    protected $appends = ['status'];

    protected $fillable = ['site_name', 'slug', 'site_status'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
	    static::creating(function ($model) {
	    	$model->slug = str_slug($model->site_name);
	    });
    }

    protected function findBySlug($slug)
    {
        return $this->where('slug', $slug)->first();
    }

    public function getStatusAttribute()
    {
        return $this->site_status ? "<i class='fas fa-check text-success'></i> Aktif" : "<i class='fas fa-times text-danger'></i> Tidak Aktif";
    }

    public function scopeFilter($query, Request $request)
    {
        if ($request->has('site_name') && !empty($request->get('site_name'))) {
            $search = strtolower($request->get('site_name'));
            $query->whereRaw('lower(site_name) like ?', '%'. $search .'%');
        }
        return $query;
    }

    public function classes()
    {
        return $this->hasMany('App\Models\Classes', 'site_id', 'id');
    }
}
